"""create_auth_tables

Revision ID: 624b931af574
Revises: 
Create Date: 2026-08-23 12:20:19.480039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '624b931af574'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Unique user identifier'),
    sa.Column('user_name', sa.String(length=100), nullable=False, comment="User's full name"),
    sa.Column('email_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of email for lookups'),
    sa.Column('email_encrypted', sa.Text(), nullable=False, comment='AES encrypted email for display'),
    sa.Column('phone_encrypted', sa.Text(), nullable=False, comment='AES encrypted phone number'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag - False means deactivated'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False, comment='Email verification status'),
    sa.Column('address', sa.Text(), nullable=True, comment='User address'),
    sa.Column('pincode', sa.String(length=10), nullable=True, comment='Postal code'),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='User preferences like theme, notifications etc'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Account creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.create_table('otp_verifications',
    sa.Column('otp_id', sa.UUID(), nullable=False, comment='Unique OTP record identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to user'),
    sa.Column('otp_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of OTP (never store plain OTP!)'),
    sa.Column('verification_type', sa.String(length=20), nullable=False, comment='Type: email_verification or password_reset'),
    sa.Column('remaining_retry', sa.Integer(), nullable=False, comment='Attempts remaining (0 = blocked)'),
    sa.Column('is_user_blocked', sa.Boolean(), nullable=False, comment='Blocked after 3 failed attempts'),
    sa.Column('blocked_at', sa.DateTime(), nullable=True, comment='When user was blocked'),
    sa.Column('otp_created_at', sa.DateTime(), nullable=False, comment='OTP generation time'),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=False, comment='OTP expiry time (10 min from creation)'),
    sa.Column('is_otp_valid', sa.Boolean(), nullable=False, comment='False when used or new OTP generated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Unique session identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to user'),
    sa.Column('device_id', sa.String(length=50), nullable=False, comment='Device identifier - stored in JWT for validation'),
    sa.Column('device_name', sa.String(length=100), nullable=True, comment='Human readable device name - Chrome on Windows'),
    sa.Column('is_session_active', sa.Boolean(), nullable=False, comment='Active session or ended (soft delete)'),
    sa.Column('session_started_at', sa.DateTime(), nullable=False, comment='Login time'),
    sa.Column('session_ended_at', sa.DateTime(), nullable=True, comment='Logout time (null if still active)'),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False, comment='Last refresh token usage'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_user_sessions_device_id'), 'user_sessions', ['device_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
